### ISSUE TITLE
Cramer's V calculation might be wrong

### ISSUE THREAD

**Issue by jpzhangvincent** [researchpy/researchpy#2] opened 2018-12-13 07:43 UTC
I got the value from the cross_tab function larger than 1. And I used the function from https://stackoverflow.com/questions/20892799/using-pandas-calculate-cram%C3%A9rs-coefficient-matrix, which gave a more accurate result.

**Comment by CoreyB10** [comment] 2019-02-18 13:48
Hey there and sorry for the long delay, are you able to provide the data that was used so I can reproduce?

**Comment by CoreyB10** [comment] 2019-02-18 14:41
Hello, I was able to produce an error which demonstrated the incorrect calculation of Cramer's V. I identified the calculation error and have update the program code which is reflected on the GitHub of the master code and has been pushed through for both pip and conda install methods. The fix in the calculation has been verified by comparing results to Stata's output.

I have closed this issue since it's been resolved. Thank you for reporting the error.

Best,

Corey


[Researchpy and Stata Cramer V comparision.pdf](https://github.com/researchpy/researchpy/files/2876099/Researchpy.and.Stata.Cramer.V.comparision.pdf)

**Closed** 2019-02-18 14:43 UTC
